### ISSUE TITLE
`AssetTagUnknown(AssignmentType(4000))` when running RGB20 & RGB25 examples

### ISSUE THREAD

**Issue by rkedez** [RGB-WG/rgb-schemata#15]
`cargo run --example rgb20` results in `thread 'main' panicked at 'invalid asset amount: AssetTagUnknown(AssignmentType(4000))', examples/rgb20.rs:68:10`

`cargo run --example rgb25` in `thread 'main' panicked at 'invalid asset amount: AssetTagUnknown(AssignmentType(4000))', examples/rgb25.rs:86:10`

This was introduced after commit 943c65d, before both examples worked fine.

**Comment by dr-orlovsky** [comment]
Fixed in the latest release
